# Generated by Django 4.2.16 on 2024-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=240, verbose_name='Lastame')),
                ('firstname', models.CharField(max_length=240, verbose_name='Firstname')),
                ('group', models.CharField(max_length=20, verbose_name='Group')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('contact_info', models.CharField(max_length=500, verbose_name='ContactInfo')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
