# Generated by Django 4.2.16 on 2024-11-18 20:04

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('oazis', 'Student')
    Student(lastname = "Иванов", firstname = "Иван", group = "36/1", email = "ivan@mail.ru", password = "ivan", contact_info = "Telegram: @ivan123").save()

class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
