# Generated by Django 4.2.16 on 2024-11-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0002_students_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact_info',
            new_name='contactInfo',
        ),
    ]
