# Generated by Django 5.1.3 on 2024-11-19 22:10

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0003_rename_contact_info_student_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=240, verbose_name='Lastname'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=240, verbose_name='Lastname')),
                ('firstname', models.CharField(max_length=240, verbose_name='Firstname')),
                ('fathername', models.CharField(max_length=240, verbose_name='Fathername')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('additionalInfo', models.CharField(max_length=500, verbose_name='AdditionalInfo')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oazis.department')),
            ],
        ),
    ]
