# Generated by Django 4.2.16 on 2024-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0004_department_alter_student_lastname_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactInfo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ContactInfo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AdditionalInfo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fathername',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Fathername'),
        ),
    ]
