# Generated by Django 4.2.16 on 2025-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0005_alter_student_contactinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Fathername'),
        ),
    ]
