# Generated by Django 4.2.16 on 2025-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0006_student_fathername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password'),
        ),
    ]
