# Generated by Django 4.2.16 on 2025-03-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0007_alter_student_email_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тема')),
                ('status', models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Ожидание'), (2, 'Одобрено'), (3, 'Защищено')], default=1, verbose_name='Статус')),
                ('has_application', models.BooleanField(default=False, verbose_name='Наличие заявления')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('backup_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_courseworks', to='oazis.teacher', verbose_name='Запасной преподаватель')),
                ('main_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_courseworks', to='oazis.teacher', verbose_name='Основной преподаватель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='oazis.student', verbose_name='Студент')),
            ],
        ),
    ]
