# Generated by Django 4.2.16 on 2025-03-22 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0008_coursework'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursework',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='has_application',
            field=models.BooleanField(default=False, verbose_name='Application signed'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Ожидание'), (2, 'Одобрено'), (3, 'Защищено')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Topic'),
        ),
    ]
