# Generated by Django 4.2.16 on 2025-04-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0009_coursework_creationdate_alter_coursework_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
