# Generated by Django 4.2.16 on 2025-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0010_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactInfo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ContactInfo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AdditionalInfo'),
        ),
    ]
