# Generated by Django 4.2.16 on 2025-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oazis', '0011_alter_student_contactinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='Password'),
        ),
    ]
